theme: jekyll-theme-midnight
title: "Theee Arcade"
description: "games and fun for everyone!"
gitorg: "https://github.com/jm1021/theeearcade"
google_analytics:
#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Theee Arcade
description: games and fun for everyone!